#!/usr/bin/env php
<?php

use Illuminate\Console\Application;
use Illuminate\Container\Container;
use Illuminate\Events\Dispatcher;

use Appsilon\LeadsEPL\Console\Commands\LoadCSVData;

if (file_exists($a = __DIR__.'/../../autoload.php')) {
    require_once $a;
} else {
    require_once __DIR__.'/vendor/autoload.php';
}

$container = new Container;
$dispatcher = new Dispatcher;
$version = "5.4"; // Laravel version

$app = new Application($container, $dispatcher, $version);

$app->add(new LoadCSVData());

$app->run();

/**
 * DUMP AND DIE
 */
function dd(... $values){
    if(!$values){
        print('ok');
        die();
    }
    foreach($values as $v){
        print_r($v);
    }
    die();
}